export const initialData = [{key: 0, seq: 'TCGAATTCCAAGACTAATAGACAGAAACAA'},
{key: 1, seq: 'GTATTAAGATAAGACACAACAACAAAATTT'},
{key: 1, seq: 'CAAATACGTCTAACGCATAATTTGATAAAG'},
{key: 1, seq: 'GTAAACAAATACCCACCTGTCAATAATAGA'},
{key: 1, seq: 'TGAAAACACATAAGCTCAATTATTTAATAG'},
{key: 1, seq: 'GTAGGACAAAATACACCCAGTATTAAAAAA'},

];
