export const initialData = [{key: 0, seq: 'TCGAATTCCAAGACTAATAGACAGAAACAA'},
{key: 1, seq: 'GTATTAAGATAAGACACAACAACAAAATTT'},
{key: 2, seq: 'CAAATACGTCTAACGCATAATTTGATAAAG'},
{key: 3, seq: 'GTAAACAAATACCCACCTGTCAATAATAGA'},
{key: 4, seq: 'TGAAAACACATAAGCTCAATTATTTAATAG'},
{key: 5, seq: 'GTAGGACAAAATACACCCAGTATTAAAAAA'},

];
